package sample;

import javafx.beans.property.DoubleProperty;
import javafx.beans.property.IntegerProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleStringProperty;

public class InHouse extends Part {

    private SimpleIntegerProperty machineID;

    //fixme Redundant constructor?

    /**
     *
     * @param id
     * @param name
     * @param price
     * @param stock
     * @param min
     * @param max
     * @param machineID
     */
    public InHouse(IntegerProperty id, SimpleStringProperty name, DoubleProperty price, IntegerProperty stock,
                   IntegerProperty min, IntegerProperty max, SimpleIntegerProperty machineID) {
        super(id, name, price, stock, min, max);
        this.machineID = machineID;
    }

    /**
     *
     * @param id
     * @param name
     * @param price
     * @param stock
     * @param min
     * @param max
     * @param machineID
     */
    public InHouse(int id, String name, double price, int stock, int min, int max, int machineID) {
        super(id, name, price, stock, min, max);
        this.machineID = new SimpleIntegerProperty(machineID);
    }

    /**
     *
     * @return
     */
    public int getMachineID() {
        return machineID.get();
    }

    //fixme how did this get here? Probably not necessary
    //ok, it's auto-generated by my IDE.  I'm tempted to leave it.  fixme run by instructor prior to submission

    /**
     *
     * @return
     */
    public SimpleIntegerProperty machineIDProperty() {
        return machineID;
    }

    /**
     *
     * @param machineID
     */
    public void setMachineID(int machineID) {
        this.machineID.set(machineID);
    }
}
